// Code generated by qtc from "GenerateDictionaryEntry.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:1
package templlmprompt

//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:1
func StreamGenerateDictionaryEntry(qw422016 *qt422016.Writer, props LlmFunctionBaseProps) {
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:1
	qw422016.N().S(`
You are a stateless software function named `)
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:1
	qw422016.N().S("`")
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:1
	qw422016.N().S(`GenerateDictionaryEntry`)
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:1
	qw422016.N().S("`")
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:1
	qw422016.N().S(`.
Your input parameters:
`)
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:1
	qw422016.N().S("`")
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:1
	qw422016.N().S(``)
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:1
	qw422016.N().S("`")
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:1
	qw422016.N().S(``)
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:1
	qw422016.N().S("`")
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:1
	qw422016.N().S(`json
[
`)
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:6
	for _, parameterDefinition := range props.ParameterDefinitions {
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:6
		qw422016.N().S(`  {
    "name": "`)
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:8
		qw422016.N().S(parameterDefinition.Name)
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:8
		qw422016.N().S(`",
    "description": "`)
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:9
		qw422016.N().S(parameterDefinition.ParameterDescription)
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:9
		qw422016.N().S(`",
    "value": "`)
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:10
		qw422016.N().S(props.ParameterValues[parameterDefinition.Name])
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:10
		qw422016.N().S(`"
  },
`)
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:12
	}
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:12
	qw422016.N().S(`]
`)
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:12
	qw422016.N().S("`")
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:12
	qw422016.N().S(``)
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:12
	qw422016.N().S("`")
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:12
	qw422016.N().S(``)
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:12
	qw422016.N().S("`")
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:12
	qw422016.N().S(`

The purpose of this function is to generate a JSON object that fits the JSON schema of the dictionary enty described by the `)
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:12
	qw422016.N().S("`")
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:12
	qw422016.N().S(`targetJsonSchema`)
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:12
	qw422016.N().S("`")
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:12
	qw422016.N().S(` parameter to the best of your ability.
- The definition entry should strive for the best dictionary level of quality and accuracy.
- The definition should include as many meanings as possible, including rare usages and folklore.

Return **only** a single, JSON object matching this schema:
`)
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:12
	qw422016.N().S("`")
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:12
	qw422016.N().S(``)
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:12
	qw422016.N().S("`")
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:12
	qw422016.N().S(``)
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:12
	qw422016.N().S("`")
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:12
	qw422016.N().S(`json
`)
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:22
	qw422016.N().S(props.ReturnJsonSchema)
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:22
	qw422016.N().S(`
`)
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:22
	qw422016.N().S("`")
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:22
	qw422016.N().S(``)
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:22
	qw422016.N().S("`")
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:22
	qw422016.N().S(``)
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:22
	qw422016.N().S("`")
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:22
	qw422016.N().S(`
`)
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:24
}

//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:24
func WriteGenerateDictionaryEntry(qq422016 qtio422016.Writer, props LlmFunctionBaseProps) {
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:24
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:24
	StreamGenerateDictionaryEntry(qw422016, props)
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:24
	qt422016.ReleaseWriter(qw422016)
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:24
}

//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:24
func GenerateDictionaryEntry(props LlmFunctionBaseProps) string {
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:24
	qb422016 := qt422016.AcquireByteBuffer()
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:24
	WriteGenerateDictionaryEntry(qb422016, props)
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:24
	qs422016 := string(qb422016.B)
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:24
	qt422016.ReleaseByteBuffer(qb422016)
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:24
	return qs422016
//line pkg/templlmprompt/GenerateDictionaryEntry.qtpl:24
}
