// Code generated by qtc from "MatchContextTermMeaningsPrompt.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:1
package templlmprompt

//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:1
import "api-go/pkg/genjsonschema"

//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:3
type MatchContextTermMeaningsProps struct {
	TermMeaningsMatchJsonSchema string
	PromptParameterDefinitions  []genjsonschema.PromptParameterDefinition
	ParamValues                 map[string]string
}

//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:10
func StreamMatchContextTermMeaningsPrompt(qw422016 *qt422016.Writer, props MatchContextTermMeaningsProps) {
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:10
	qw422016.N().S(`
You are a stateless software function named `)
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:10
	qw422016.N().S("`")
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:10
	qw422016.N().S(`MatchContextTermMeanings`)
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:10
	qw422016.N().S("`")
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:10
	qw422016.N().S(`.
Your input parameters:
`)
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:10
	qw422016.N().S("`")
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:10
	qw422016.N().S(``)
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:10
	qw422016.N().S("`")
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:10
	qw422016.N().S(``)
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:10
	qw422016.N().S("`")
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:10
	qw422016.N().S(`json
[
`)
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:15
	for _, parameterDefinition := range props.PromptParameterDefinitions {
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:15
		qw422016.N().S(`  {
    "name": "`)
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:17
		qw422016.N().S(parameterDefinition.Name)
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:17
		qw422016.N().S(`",
    "description": "`)
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:18
		qw422016.N().S(parameterDefinition.ParameterDescription)
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:18
		qw422016.N().S(`",
    "value": "`)
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:19
		qw422016.N().S(props.ParamValues[parameterDefinition.Name])
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:19
		qw422016.N().S(`"
  },
`)
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:21
	}
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:21
	qw422016.N().S(`]
`)
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:21
	qw422016.N().S("`")
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:21
	qw422016.N().S(``)
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:21
	qw422016.N().S("`")
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:21
	qw422016.N().S(``)
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:21
	qw422016.N().S("`")
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:21
	qw422016.N().S(`

The purpose of this function is to determine which meaning(s) of a dictionary entry best match a given context term.

Your task:
1. Analyze the provided dictionary entry (AiDictionaryEntryConfig) containing multiple possible meanings for a term
2. Examine the contextual usage of the term (AiContextTerm) as it appears in a specific context
3. Identify which meaning(s) from the dictionary entry best match how the term is used in the specific context
4. Return a list of meaning IDs that match the context term, in order of most likely to least likely match

When determining the appropriate meaning(s):
- Consider the grammatical form and context notes of the term
- Analyze the example usage provided in the context
- Compare against all meaning definitions in the dictionary entry
- You may return multiple meaning IDs if the context could potentially match multiple meanings

Return **only** a JSON array of meaning ID strings that match the context. Example: ["term-0", "term-3"]

`)
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:21
	qw422016.N().S("`")
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:21
	qw422016.N().S(``)
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:21
	qw422016.N().S("`")
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:21
	qw422016.N().S(``)
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:21
	qw422016.N().S("`")
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:21
	qw422016.N().S(`json
`)
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:42
	qw422016.N().S(props.TermMeaningsMatchJsonSchema)
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:42
	qw422016.N().S(`
`)
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:42
	qw422016.N().S("`")
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:42
	qw422016.N().S(``)
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:42
	qw422016.N().S("`")
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:42
	qw422016.N().S(``)
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:42
	qw422016.N().S("`")
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:42
	qw422016.N().S(`
`)
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:44
}

//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:44
func WriteMatchContextTermMeaningsPrompt(qq422016 qtio422016.Writer, props MatchContextTermMeaningsProps) {
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:44
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:44
	StreamMatchContextTermMeaningsPrompt(qw422016, props)
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:44
	qt422016.ReleaseWriter(qw422016)
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:44
}

//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:44
func MatchContextTermMeaningsPrompt(props MatchContextTermMeaningsProps) string {
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:44
	qb422016 := qt422016.AcquireByteBuffer()
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:44
	WriteMatchContextTermMeaningsPrompt(qb422016, props)
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:44
	qs422016 := string(qb422016.B)
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:44
	qt422016.ReleaseByteBuffer(qb422016)
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:44
	return qs422016
//line pkg/templlmprompt/MatchContextTermMeaningsPrompt.qtpl:44
}
