// Code generated by qtc from "MatchContextTermMeanings.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:1
package templlmprompt

//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:1
func StreamMatchContextTermMeanings(qw422016 *qt422016.Writer, props LlmFunctionBaseProps) {
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:1
	qw422016.N().S(`
You are a stateless software function named `)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:1
	qw422016.N().S("`")
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:1
	qw422016.N().S(`MatchContextTermMeanings`)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:1
	qw422016.N().S("`")
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:1
	qw422016.N().S(`.
Your input parameters:
`)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:1
	qw422016.N().S("`")
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:1
	qw422016.N().S(``)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:1
	qw422016.N().S("`")
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:1
	qw422016.N().S(``)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:1
	qw422016.N().S("`")
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:1
	qw422016.N().S(`json
[
`)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:6
	for _, parameterDefinition := range props.ParameterDefinitions {
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:6
		qw422016.N().S(`  {
    "name": "`)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:7
		qw422016.N().S(parameterDefinition.Name)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:7
		qw422016.N().S(`",
    "description": "`)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:8
		qw422016.N().S(parameterDefinition.ParameterDescription)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:8
		qw422016.N().S(`",
    "value": "`)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:9
		qw422016.N().S(props.ParameterValues[parameterDefinition.Name])
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:9
		qw422016.N().S(`"
  },
`)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:11
	}
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:11
	qw422016.N().S(`]
`)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:11
	qw422016.N().S("`")
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:11
	qw422016.N().S(``)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:11
	qw422016.N().S("`")
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:11
	qw422016.N().S(``)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:11
	qw422016.N().S("`")
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:11
	qw422016.N().S(`

The purpose of this function is to determine which meaning(s) of a dictionary entry best match a given context term.

Your task:
1. Analyze the provided dictionary entry (AiDictionaryEntryConfig) containing multiple possible meanings for a term
2. Examine the contextual usage of the term (AiContextTerm) as it appears in a specific context
3. Identify which meaning(s) from the dictionary entry best match how the term is used in the specific context
4. Return a list of meaning IDs that match the context term, in order of most likely to least likely match

When determining the appropriate meaning(s):
- Consider the grammatical form and context notes of the term
- Analyze the example usage provided in the context
- Compare against all meaning definitions in the dictionary entry
- You may return multiple meaning IDs if the context could potentially match multiple meanings

Return **only** a JSON array of meaning ID strings that match the context. Example: ["term-0", "term-3"]

`)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:11
	qw422016.N().S("`")
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:11
	qw422016.N().S(``)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:11
	qw422016.N().S("`")
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:11
	qw422016.N().S(``)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:11
	qw422016.N().S("`")
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:11
	qw422016.N().S(`json
`)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:31
	qw422016.N().S(props.ReturnJsonSchema)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:31
	qw422016.N().S(`
`)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:31
	qw422016.N().S("`")
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:31
	qw422016.N().S(``)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:31
	qw422016.N().S("`")
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:31
	qw422016.N().S(``)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:31
	qw422016.N().S("`")
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:31
	qw422016.N().S(`
`)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:33
}

//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:33
func WriteMatchContextTermMeanings(qq422016 qtio422016.Writer, props LlmFunctionBaseProps) {
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:33
	qw422016 := qt422016.AcquireWriter(qq422016)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:33
	StreamMatchContextTermMeanings(qw422016, props)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:33
	qt422016.ReleaseWriter(qw422016)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:33
}

//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:33
func MatchContextTermMeanings(props LlmFunctionBaseProps) string {
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:33
	qb422016 := qt422016.AcquireByteBuffer()
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:33
	WriteMatchContextTermMeanings(qb422016, props)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:33
	qs422016 := string(qb422016.B)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:33
	qt422016.ReleaseByteBuffer(qb422016)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:33
	return qs422016
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/MatchContextTermMeanings.qtpl:33
}
