// Code generated by qtc from "WordSplitterPrompt.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line pkg/templlmprompt/WordSplitterPrompt.qtpl:1
package templlmprompt

//line pkg/templlmprompt/WordSplitterPrompt.qtpl:1
import "api-go/pkg/genjsonschema"

//line pkg/templlmprompt/WordSplitterPrompt.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pkg/templlmprompt/WordSplitterPrompt.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pkg/templlmprompt/WordSplitterPrompt.qtpl:3
type WordSplitterProps struct {
	TermNeutralJsonSchema      string
	PromptParameterDefinitions []genjsonschema.PromptParameterDefinition
	ParamValues                map[string]string
}

//line pkg/templlmprompt/WordSplitterPrompt.qtpl:10
func StreamWordSplitterPrompt(qw422016 *qt422016.Writer, props WordSplitterProps) {
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:10
	qw422016.N().S(`
You are a stateless software function named `)
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:10
	qw422016.N().S("`")
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:10
	qw422016.N().S(`WordSplitter`)
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:10
	qw422016.N().S("`")
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:10
	qw422016.N().S(`.
Your input parameters:
`)
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:10
	qw422016.N().S("`")
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:10
	qw422016.N().S(``)
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:10
	qw422016.N().S("`")
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:10
	qw422016.N().S(``)
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:10
	qw422016.N().S("`")
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:10
	qw422016.N().S(`json
[
`)
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:15
	for _, parameterDefinition := range props.PromptParameterDefinitions {
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:15
		qw422016.N().S(`  {
    "name": "`)
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:17
		qw422016.N().S(parameterDefinition.Name)
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:17
		qw422016.N().S(`",
    "description": "`)
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:18
		qw422016.N().S(parameterDefinition.ParameterDescription)
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:18
		qw422016.N().S(`",
    "value": "`)
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:19
		qw422016.N().S(props.ParamValues[parameterDefinition.Name])
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:19
		qw422016.N().S(`"
  },
`)
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:21
	}
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:21
	qw422016.N().S(`]
`)
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:21
	qw422016.N().S("`")
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:21
	qw422016.N().S(``)
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:21
	qw422016.N().S("`")
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:21
	qw422016.N().S(``)
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:21
	qw422016.N().S("`")
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:21
	qw422016.N().S(`

The purpose of this function is to split text into individual words and convert them to their neutral grammatical forms while preserving their original form:

1. Identify ALL words in the text, including:
   - Particles, articles, and functional words
   - Repeated instances of the same word
   - EXCLUDE all punctuation marks and whitespace

2. For each word:
   - Store its exact original form as it appears in the text in the `)
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:21
	qw422016.N().S("`")
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:21
	qw422016.N().S(`contextForm`)
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:21
	qw422016.N().S("`")
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:21
	qw422016.N().S(` field
   - Determine its base/neutral form for the `)
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:21
	qw422016.N().S("`")
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:21
	qw422016.N().S(`neutralForm`)
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:21
	qw422016.N().S("`")
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:21
	qw422016.N().S(` field:
     - For verbs: infinitive form
     - For nouns: singular form
     - For adjectives: masculine singular form
     - For other word types: appropriate dictionary form
   
3. IMPORTANT: The list must be ordered exactly as the terms appear in the original text

Return **only** a single, JSON object matching this schema:
`)
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:21
	qw422016.N().S("`")
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:21
	qw422016.N().S(``)
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:21
	qw422016.N().S("`")
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:21
	qw422016.N().S(``)
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:21
	qw422016.N().S("`")
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:21
	qw422016.N().S(`json
`)
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:44
	qw422016.N().S(props.TermNeutralJsonSchema)
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:44
	qw422016.N().S(`
`)
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:44
	qw422016.N().S("`")
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:44
	qw422016.N().S(``)
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:44
	qw422016.N().S("`")
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:44
	qw422016.N().S(``)
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:44
	qw422016.N().S("`")
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:44
	qw422016.N().S(`
`)
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:46
}

//line pkg/templlmprompt/WordSplitterPrompt.qtpl:46
func WriteWordSplitterPrompt(qq422016 qtio422016.Writer, props WordSplitterProps) {
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:46
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:46
	StreamWordSplitterPrompt(qw422016, props)
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:46
	qt422016.ReleaseWriter(qw422016)
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:46
}

//line pkg/templlmprompt/WordSplitterPrompt.qtpl:46
func WordSplitterPrompt(props WordSplitterProps) string {
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:46
	qb422016 := qt422016.AcquireByteBuffer()
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:46
	WriteWordSplitterPrompt(qb422016, props)
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:46
	qs422016 := string(qb422016.B)
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:46
	qt422016.ReleaseByteBuffer(qb422016)
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:46
	return qs422016
//line pkg/templlmprompt/WordSplitterPrompt.qtpl:46
}
