// Code generated by qtc from "WordSplitterPrompt.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:1
package templlmprompt

//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:1
func StreamWordSplitterPrompt(qw422016 *qt422016.Writer, props LlmFunctionBaseProps) {
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:1
	qw422016.N().S(`
You are a stateless software function named `)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:1
	qw422016.N().S("`")
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:1
	qw422016.N().S(`WordSplitter`)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:1
	qw422016.N().S("`")
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:1
	qw422016.N().S(`.
Your input parameters:
`)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:1
	qw422016.N().S("`")
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:1
	qw422016.N().S(``)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:1
	qw422016.N().S("`")
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:1
	qw422016.N().S(``)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:1
	qw422016.N().S("`")
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:1
	qw422016.N().S(`json
[
`)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:6
	for _, parameterDefinition := range props.ParameterDefinitions {
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:6
		qw422016.N().S(`  {
    "name": "`)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:8
		qw422016.N().S(parameterDefinition.Name)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:8
		qw422016.N().S(`",
    "description": "`)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:9
		qw422016.N().S(parameterDefinition.ParameterDescription)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:9
		qw422016.N().S(`",
    "value": "`)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:10
		qw422016.N().S(props.ParameterValues[parameterDefinition.Name])
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:10
		qw422016.N().S(`"
  },
`)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:12
	}
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:12
	qw422016.N().S(`]
`)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:12
	qw422016.N().S("`")
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:12
	qw422016.N().S(``)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:12
	qw422016.N().S("`")
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:12
	qw422016.N().S(``)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:12
	qw422016.N().S("`")
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:12
	qw422016.N().S(`

The purpose of this function is to split text into individual words and convert them to their neutral grammatical forms while preserving their original form:

1. Identify ALL words in the text, including:
   - Particles, articles, and functional words
   - Repeated instances of the same word
   - EXCLUDE all punctuation marks and whitespace

2. For each word:
   - Store its exact original form as it appears in the text in the `)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:12
	qw422016.N().S("`")
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:12
	qw422016.N().S(`contextForm`)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:12
	qw422016.N().S("`")
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:12
	qw422016.N().S(` field
   - Determine its base/neutral form for the `)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:12
	qw422016.N().S("`")
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:12
	qw422016.N().S(`neutralForm`)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:12
	qw422016.N().S("`")
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:12
	qw422016.N().S(` field:
     - For verbs: infinitive form
     - For nouns: singular form
     - For adjectives: masculine singular form
     - For other word types: appropriate dictionary form
   
3. IMPORTANT: The list must be ordered exactly as the terms appear in the original text

Return **only** a single, JSON object matching this schema:
`)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:12
	qw422016.N().S("`")
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:12
	qw422016.N().S(``)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:12
	qw422016.N().S("`")
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:12
	qw422016.N().S(``)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:12
	qw422016.N().S("`")
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:12
	qw422016.N().S(`json
`)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:35
	qw422016.N().S(props.ReturnJsonSchema)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:35
	qw422016.N().S(`
`)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:35
	qw422016.N().S("`")
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:35
	qw422016.N().S(``)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:35
	qw422016.N().S("`")
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:35
	qw422016.N().S(``)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:35
	qw422016.N().S("`")
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:35
	qw422016.N().S(`
`)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:37
}

//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:37
func WriteWordSplitterPrompt(qq422016 qtio422016.Writer, props LlmFunctionBaseProps) {
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:37
	qw422016 := qt422016.AcquireWriter(qq422016)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:37
	StreamWordSplitterPrompt(qw422016, props)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:37
	qt422016.ReleaseWriter(qw422016)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:37
}

//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:37
func WordSplitterPrompt(props LlmFunctionBaseProps) string {
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:37
	qb422016 := qt422016.AcquireByteBuffer()
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:37
	WriteWordSplitterPrompt(qb422016, props)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:37
	qs422016 := string(qb422016.B)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:37
	qt422016.ReleaseByteBuffer(qb422016)
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:37
	return qs422016
//line /Users/egorkolds/code/project-hobby/api-go/pkg/templlmprompt/WordSplitterPrompt.qtpl:37
}
