services:
  postgres:
    image: postgres:15-alpine
    container_name: langtools-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: langtools
      POSTGRES_USER: langtools
      POSTGRES_PASSWORD: langtools_dev_password
    ports:
      # Use a different port to avoid collisions
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U langtools -d langtools"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: langtools-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://langtools:langtools_dev_password@postgres:5432/langtools
    volumes:
      - .:/workspace
    depends_on:
      - postgres
    working_dir: /workspace
    command: uv run python run_api.py

volumes:
  postgres_data:
    driver: local
