"""empty message

Revision ID: 525a1a6cecde
Revises: e6a268b72a19
Create Date: 2025-08-24 22:42:10.140668

"""

# for `sqlmodel.sql` access
# pyright: reportAttributeAccessIssue=false
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "525a1a6cecde"
down_revision: Union[str, Sequence[str], None] = "e6a268b72a19"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_r_meaning_translation_fsrs_auth_user_id"), table_name="r_fsrs_meaning")
    op.drop_index(
        op.f("ix_r_meaning_translation_fsrs_dictionary_entry_id"), table_name="r_fsrs_meaning"
    )
    op.drop_index(op.f("ix_r_meaning_translation_fsrs_fsrs_id"), table_name="r_fsrs_meaning")
    op.drop_index(op.f("ix_r_meaning_translation_fsrs_id"), table_name="r_fsrs_meaning")
    op.drop_index(
        op.f("ix_r_meaning_translation_fsrs_meaning_local_id"), table_name="r_fsrs_meaning"
    )
    op.create_index(
        op.f("ix_r_fsrs_meaning_auth_user_id"), "r_fsrs_meaning", ["auth_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_r_fsrs_meaning_dictionary_entry_id"),
        "r_fsrs_meaning",
        ["dictionary_entry_id"],
        unique=False,
    )
    op.create_index(op.f("ix_r_fsrs_meaning_fsrs_id"), "r_fsrs_meaning", ["fsrs_id"], unique=True)
    op.create_index(op.f("ix_r_fsrs_meaning_id"), "r_fsrs_meaning", ["id"], unique=False)
    op.create_index(
        op.f("ix_r_fsrs_meaning_meaning_local_id"),
        "r_fsrs_meaning",
        ["meaning_local_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_r_fsrs_meaning_meaning_local_id"), table_name="r_fsrs_meaning")
    op.drop_index(op.f("ix_r_fsrs_meaning_id"), table_name="r_fsrs_meaning")
    op.drop_index(op.f("ix_r_fsrs_meaning_fsrs_id"), table_name="r_fsrs_meaning")
    op.drop_index(op.f("ix_r_fsrs_meaning_dictionary_entry_id"), table_name="r_fsrs_meaning")
    op.drop_index(op.f("ix_r_fsrs_meaning_auth_user_id"), table_name="r_fsrs_meaning")
    op.create_index(
        op.f("ix_r_meaning_translation_fsrs_meaning_local_id"),
        "r_fsrs_meaning",
        ["meaning_local_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_r_meaning_translation_fsrs_id"), "r_fsrs_meaning", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_r_meaning_translation_fsrs_fsrs_id"), "r_fsrs_meaning", ["fsrs_id"], unique=True
    )
    op.create_index(
        op.f("ix_r_meaning_translation_fsrs_dictionary_entry_id"),
        "r_fsrs_meaning",
        ["dictionary_entry_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_r_meaning_translation_fsrs_auth_user_id"),
        "r_fsrs_meaning",
        ["auth_user_id"],
        unique=False,
    )
    # ### end Alembic commands ###
