"""add fsrs tables and relations

Revision ID: 7e35122c1731
Revises: 4f1e3b2c1d2e
Create Date: 2025-08-12 01:19:26.858431

"""
# for `sqlmodel.sql` access
# pyright: reportAttributeAccessIssue=false
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7e35122c1731'
down_revision: Union[str, Sequence[str], None] = '4f1e3b2c1d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fsrs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('due', sa.DateTime(), nullable=False),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('last_review', sa.DateTime(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fsrs_id'), 'fsrs', ['id'], unique=False)
    op.create_table('r_meaning_translation_fsrs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auth_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fsrs_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dictionary_entry_translation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meaning_local_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['auth_user_id'], ['auth_user.id'], ),
    sa.ForeignKeyConstraint(['dictionary_entry_translation_id'], ['dictionary_entry_translation.id'], ),
    sa.ForeignKeyConstraint(['fsrs_id'], ['fsrs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_user_id', 'dictionary_entry_translation_id', 'meaning_local_id', name='uq_user_translation_meaning')
    )
    op.create_index(op.f('ix_r_meaning_translation_fsrs_auth_user_id'), 'r_meaning_translation_fsrs', ['auth_user_id'], unique=False)
    op.create_index(op.f('ix_r_meaning_translation_fsrs_dictionary_entry_translation_id'), 'r_meaning_translation_fsrs', ['dictionary_entry_translation_id'], unique=False)
    op.create_index(op.f('ix_r_meaning_translation_fsrs_fsrs_id'), 'r_meaning_translation_fsrs', ['fsrs_id'], unique=False)
    op.create_index(op.f('ix_r_meaning_translation_fsrs_id'), 'r_meaning_translation_fsrs', ['id'], unique=False)
    op.create_index(op.f('ix_r_meaning_translation_fsrs_meaning_local_id'), 'r_meaning_translation_fsrs', ['meaning_local_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_r_meaning_translation_fsrs_meaning_local_id'), table_name='r_meaning_translation_fsrs')
    op.drop_index(op.f('ix_r_meaning_translation_fsrs_id'), table_name='r_meaning_translation_fsrs')
    op.drop_index(op.f('ix_r_meaning_translation_fsrs_fsrs_id'), table_name='r_meaning_translation_fsrs')
    op.drop_index(op.f('ix_r_meaning_translation_fsrs_dictionary_entry_translation_id'), table_name='r_meaning_translation_fsrs')
    op.drop_index(op.f('ix_r_meaning_translation_fsrs_auth_user_id'), table_name='r_meaning_translation_fsrs')
    op.drop_table('r_meaning_translation_fsrs')
    op.drop_index(op.f('ix_fsrs_id'), table_name='fsrs')
    op.drop_table('fsrs')
    # ### end Alembic commands ###
