"""empty message

Revision ID: d056f23efb11
Revises: 5efb67bdf3be
Create Date: 2025-08-24 20:37:55.124214

"""

# for `sqlmodel.sql` access
# pyright: reportAttributeAccessIssue=false
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d056f23efb11"
down_revision: Union[str, Sequence[str], None] = "5efb67bdf3be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "r_meaning_translation_fsrs",
        sa.Column("dictionary_entry_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.create_index(
        op.f("ix_r_meaning_translation_fsrs_dictionary_entry_id"),
        "r_meaning_translation_fsrs",
        ["dictionary_entry_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "r_meaning_translation_fsrs", "dictionary_entry", ["dictionary_entry_id"], ["id"]
    )

    # Migrate data from dictionary_entry_translation to dictionary_entry
    op.execute("""
UPDATE r_meaning_translation_fsrs 
SET dictionary_entry_id = (
    SELECT dictionary_entry_id 
    FROM dictionary_entry_translation 
    WHERE dictionary_entry_translation.id = \
r_meaning_translation_fsrs.dictionary_entry_translation_id
)
    """)

    # Make dictionary_entry_id non-nullable after data migration
    op.alter_column("r_meaning_translation_fsrs", "dictionary_entry_id", nullable=False)

    op.drop_index(
        op.f("ix_r_meaning_translation_fsrs_dictionary_entry_translation_id"),
        table_name="r_meaning_translation_fsrs",
    )
    op.drop_constraint(
        op.f("r_meaning_translation_fsrs_dictionary_entry_translation_id_fkey"),
        "r_meaning_translation_fsrs",
        type_="foreignkey",
    )
    op.drop_column("r_meaning_translation_fsrs", "dictionary_entry_translation_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "r_meaning_translation_fsrs",
        sa.Column(
            "dictionary_entry_translation_id", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(
        op.f("r_meaning_translation_fsrs_dictionary_entry_id_fkey"),
        "r_meaning_translation_fsrs",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("r_meaning_translation_fsrs_dictionary_entry_translation_id_fkey"),
        "r_meaning_translation_fsrs",
        "dictionary_entry_translation",
        ["dictionary_entry_translation_id"],
        ["id"],
    )
    op.drop_index(
        op.f("ix_r_meaning_translation_fsrs_dictionary_entry_id"),
        table_name="r_meaning_translation_fsrs",
    )
    op.create_index(
        op.f("ix_r_meaning_translation_fsrs_dictionary_entry_translation_id"),
        "r_meaning_translation_fsrs",
        ["dictionary_entry_translation_id"],
        unique=False,
    )
    op.drop_column("r_meaning_translation_fsrs", "dictionary_entry_id")
    # ### end Alembic commands ###
