"""Add created_at and updated_at columns to all tables

Revision ID: f30656839bba
Revises: d91aedc23fe3
Create Date: 2025-08-08 01:33:01.267501

"""

# for `sqlmodel.sql` access
# pyright: reportAttributeAccessIssue=false
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f30656839bba"
down_revision: Union[str, Sequence[str], None] = "d91aedc23fe3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add timestamp columns with defaults for existing records
    current_time = sa.text("CURRENT_TIMESTAMP")

    # Add columns as nullable with server defaults first
    op.add_column(
        "auth_password",
        sa.Column("created_at", sa.DateTime(), nullable=True, server_default=current_time),
    )
    op.add_column(
        "auth_password",
        sa.Column("updated_at", sa.DateTime(), nullable=True, server_default=current_time),
    )
    op.add_column(
        "auth_user",
        sa.Column("created_at", sa.DateTime(), nullable=True, server_default=current_time),
    )
    op.add_column(
        "auth_user",
        sa.Column("updated_at", sa.DateTime(), nullable=True, server_default=current_time),
    )
    op.add_column(
        "profile",
        sa.Column("created_at", sa.DateTime(), nullable=True, server_default=current_time),
    )
    op.add_column(
        "profile",
        sa.Column("updated_at", sa.DateTime(), nullable=True, server_default=current_time),
    )

    # Make the columns non-nullable now that they have values
    op.alter_column("auth_password", "created_at", nullable=False)
    op.alter_column("auth_password", "updated_at", nullable=False)
    op.alter_column("auth_user", "created_at", nullable=False)
    op.alter_column("auth_user", "updated_at", nullable=False)
    op.alter_column("profile", "created_at", nullable=False)
    op.alter_column("profile", "updated_at", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profile", "updated_at")
    op.drop_column("profile", "created_at")
    op.drop_column("auth_user", "updated_at")
    op.drop_column("auth_user", "created_at")
    op.drop_column("auth_password", "updated_at")
    op.drop_column("auth_password", "created_at")
    # ### end Alembic commands ###
