name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      working-directory: langtools-ai
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    
    - name: Run type checking
      working-directory: langtools-ai
      run: |
        mypy src/langtools/ai/
    
    - name: Run linting
      working-directory: langtools-ai
      run: |
        ruff check src/ tests/
    
    - name: Run tests
      working-directory: langtools-ai
      run: |
        pytest tests/ -v --cov=src/langtools/ai/ --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./langtools-ai/coverage.xml
        flags: unittests
        name: codecov-umbrella