name: vocabo
description: "Offline-first language learning app with local LLM capabilities."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.9
  go_router: ^13.1.0
  
  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  
  # Utilities
  logger: ^2.0.2
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  
  # LLM Integration
  # TODO: Add appropriate LLM package after evaluation
  # Candidates: flutter_llm, google_ml_kit, tflite_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
  
  assets:
    - assets/models/
    - assets/test_data/
