// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type HistoryAi struct {
	Id            string           `json:"id"`
	UserId        pgtype.Text      `json:"user_id"`
	OperationJson []byte           `json:"operation_json"`
	ResponseJson  []byte           `json:"response_json"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type HistoryText struct {
	Id        string           `json:"id"`
	TextInput string           `json:"text_input"`
	UserId    string           `json:"user_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type HistoryWord struct {
	Id        string           `json:"id"`
	Word      string           `json:"word"`
	UserId    string           `json:"user_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type UserAuth struct {
	Id     string `json:"id"`
	UserId string `json:"user_id"`
	Token  string `json:"token"`
}

type UserInfo struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

type Word struct {
	Num    int32  `json:"num"`
	Json   []byte `json:"json"`
	UserId string `json:"user_id"`
}
