// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user_info.sql

package sqlgen

import (
	"context"
)

const getUserInfo = `-- name: GetUserInfo :one
SELECT
  id, name
FROM
  user_info
WHERE
  id = $1
`

func (q *Queries) GetUserInfo(ctx context.Context, id string) (UserInfo, error) {
	row := q.db.QueryRow(ctx, getUserInfo, id)
	var i UserInfo
	err := row.Scan(&i.Id, &i.Name)
	return i, err
}
