// Code generated by qtc from "CreateSignUpCode.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line ../../pkg/templatecypher/CreateSignUpCode.qtpl:1
package templatecypher

//line ../../pkg/templatecypher/CreateSignUpCode.qtpl:1
import "api-go/pkg/modelsurreal"

//line ../../pkg/templatecypher/CreateSignUpCode.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line ../../pkg/templatecypher/CreateSignUpCode.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line ../../pkg/templatecypher/CreateSignUpCode.qtpl:3
func StreamCreateSignUpCode(qw422016 *qt422016.Writer, signUpCode modelsurreal.SignUpCode) {
//line ../../pkg/templatecypher/CreateSignUpCode.qtpl:3
	qw422016.N().S(`
CREATE (signUpCode:SignUpCode {
  Email: $Email,
  Code: $Code,
  CreatedAt: datetime(),
  UpdatedAt: datetime(),
  DeletedAt: null
})
`)
//line ../../pkg/templatecypher/CreateSignUpCode.qtpl:11
}

//line ../../pkg/templatecypher/CreateSignUpCode.qtpl:11
func WriteCreateSignUpCode(qq422016 qtio422016.Writer, signUpCode modelsurreal.SignUpCode) {
//line ../../pkg/templatecypher/CreateSignUpCode.qtpl:11
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../pkg/templatecypher/CreateSignUpCode.qtpl:11
	StreamCreateSignUpCode(qw422016, signUpCode)
//line ../../pkg/templatecypher/CreateSignUpCode.qtpl:11
	qt422016.ReleaseWriter(qw422016)
//line ../../pkg/templatecypher/CreateSignUpCode.qtpl:11
}

//line ../../pkg/templatecypher/CreateSignUpCode.qtpl:11
func CreateSignUpCode(signUpCode modelsurreal.SignUpCode) string {
//line ../../pkg/templatecypher/CreateSignUpCode.qtpl:11
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../pkg/templatecypher/CreateSignUpCode.qtpl:11
	WriteCreateSignUpCode(qb422016, signUpCode)
//line ../../pkg/templatecypher/CreateSignUpCode.qtpl:11
	qs422016 := string(qb422016.B)
//line ../../pkg/templatecypher/CreateSignUpCode.qtpl:11
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../pkg/templatecypher/CreateSignUpCode.qtpl:11
	return qs422016
//line ../../pkg/templatecypher/CreateSignUpCode.qtpl:11
}
