/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type MessageUnion = MessageCreateWord | MessageParseText | MessageDefineWord;

export interface MessageCreateWord {
  name: "createWord";
  data: {
    word: Word;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * A detailed representation of a word, including its original and neutral forms, pronunciations, translations, definitions, origin, and usage examples.
 */
export interface Word {
  /**
   * The original language of the word in a BCP 47 format.
   */
  languageOriginal: string;
  /**
   * The language the word is translated to in a BCP 47 format.
   */
  languageTranslated: string;
  /**
   * The original word given, in the exact same grammatic form, capitalized.
   */
  originalWord: string;
  /**
   * The word in a neutral grammatic form.
   */
  neutralForm: string;
  /**
   * A pronunciation of the original word given.
   */
  pronounciation: string;
  /**
   * An extensive translation to English, the more words the better.
   */
  translation: string;
  /**
   * Common synonyms in the original language.
   */
  synonyms: string[];
  /**
   * An extensive definition in the original language.
   */
  definitionOriginal: string;
  /**
   * An extensive definition in English.
   */
  definitionTranslated: string;
  /**
   * The root parts of the word and the origin in English. If the original form from Part 1 is different from the neutral grammatic form from Part 2, explain that difference including all the details.
   */
  origin: string;
  /**
   * Three sentence examples of the usage of the original word in the same grammatic form followed by an English translation. The sentence and the translation should be separated by one new line, while the examples themselves should be separated by three new lines. If there was a context from which that word was taken, include a phrase from that context in examples, replacing the first example.
   */
  examples: {
    /**
     * An example sentence in the original language using the word.
     */
    original: string;
    /**
     * The English translation of the example sentence.
     */
    translation: string;
    [k: string]: unknown;
  }[];
  /**
   * The date and time when the word was exported to CSV.
   */
  csvExportedAt?: string;
  [k: string]: unknown;
}
export interface MessageParseText {
  name: "parseText";
  data: {
    text: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface MessageDefineWord {
  name: "defineWord";
  data: {
    wordString: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
