// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package genjsonschema

import "encoding/json"
import "fmt"

type ActionSignUpByEmailResponse struct {
	// AuthToken corresponds to the JSON schema field "authToken".
	AuthToken *string `json:"authToken" yaml:"authToken" mapstructure:"authToken"`

	// Data corresponds to the JSON schema field "data".
	Data ActionSignUpByEmailResponseData `json:"data" yaml:"data" mapstructure:"data"`

	// Errors corresponds to the JSON schema field "errors".
	Errors []AppError `json:"errors" yaml:"errors" mapstructure:"errors"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Name corresponds to the JSON schema field "name".
	Name interface{} `json:"name" yaml:"name" mapstructure:"name"`

	// ResponseForId corresponds to the JSON schema field "responseForId".
	ResponseForId string `json:"responseForId" yaml:"responseForId" mapstructure:"responseForId"`
}

type ActionSignUpByEmailResponseData struct {
	// ActionName corresponds to the JSON schema field "actionName".
	ActionName interface{} `json:"actionName" yaml:"actionName" mapstructure:"actionName"`

	// ActionParams corresponds to the JSON schema field "actionParams".
	ActionParams ActionSignUpByEmailResponseDataActionParams `json:"actionParams" yaml:"actionParams" mapstructure:"actionParams"`
}

type ActionSignUpByEmailResponseDataActionParams map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ActionSignUpByEmailResponseData) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["actionName"]; raw != nil && !ok {
		return fmt.Errorf("field actionName in ActionSignUpByEmailResponseData: required")
	}
	if _, ok := raw["actionParams"]; raw != nil && !ok {
		return fmt.Errorf("field actionParams in ActionSignUpByEmailResponseData: required")
	}
	type Plain ActionSignUpByEmailResponseData
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = ActionSignUpByEmailResponseData(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ActionSignUpByEmailResponse) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["authToken"]; raw != nil && !ok {
		return fmt.Errorf("field authToken in ActionSignUpByEmailResponse: required")
	}
	if _, ok := raw["data"]; raw != nil && !ok {
		return fmt.Errorf("field data in ActionSignUpByEmailResponse: required")
	}
	if _, ok := raw["errors"]; raw != nil && !ok {
		return fmt.Errorf("field errors in ActionSignUpByEmailResponse: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in ActionSignUpByEmailResponse: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in ActionSignUpByEmailResponse: required")
	}
	if _, ok := raw["responseForId"]; raw != nil && !ok {
		return fmt.Errorf("field responseForId in ActionSignUpByEmailResponse: required")
	}
	type Plain ActionSignUpByEmailResponse
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = ActionSignUpByEmailResponse(plain)
	return nil
}
