// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package genjsonschema

import "encoding/json"
import "fmt"

type ActionBase struct {
	// Data corresponds to the JSON schema field "data".
	Data ActionBaseData `json:"data" yaml:"data" mapstructure:"data"`

	// Errors corresponds to the JSON schema field "errors".
	Errors []AppError `json:"errors" yaml:"errors" mapstructure:"errors"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Name corresponds to the JSON schema field "name".
	Name interface{} `json:"name" yaml:"name" mapstructure:"name"`

	// ResponseForId corresponds to the JSON schema field "responseForId".
	ResponseForId *string `json:"responseForId,omitempty" yaml:"responseForId,omitempty" mapstructure:"responseForId,omitempty"`
}

type ActionBaseData struct {
	// ActionName corresponds to the JSON schema field "actionName".
	ActionName ActionName `json:"actionName" yaml:"actionName" mapstructure:"actionName"`

	// ActionParams corresponds to the JSON schema field "actionParams".
	ActionParams ActionBaseDataActionParams `json:"actionParams" yaml:"actionParams" mapstructure:"actionParams"`
}

type ActionBaseDataActionParams map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ActionBaseData) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["actionName"]; raw != nil && !ok {
		return fmt.Errorf("field actionName in ActionBaseData: required")
	}
	if _, ok := raw["actionParams"]; raw != nil && !ok {
		return fmt.Errorf("field actionParams in ActionBaseData: required")
	}
	type Plain ActionBaseData
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = ActionBaseData(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ActionBase) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["data"]; raw != nil && !ok {
		return fmt.Errorf("field data in ActionBase: required")
	}
	if _, ok := raw["errors"]; raw != nil && !ok {
		return fmt.Errorf("field errors in ActionBase: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in ActionBase: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in ActionBase: required")
	}
	type Plain ActionBase
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = ActionBase(plain)
	return nil
}
