// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package genjsonschema

import "encoding/json"
import "fmt"

type ActionCreateFieldConfig struct {
	// AuthToken corresponds to the JSON schema field "authToken".
	AuthToken *string `json:"authToken" yaml:"authToken" mapstructure:"authToken"`

	// Data corresponds to the JSON schema field "data".
	Data ActionCreateFieldConfigData `json:"data" yaml:"data" mapstructure:"data"`

	// Errors corresponds to the JSON schema field "errors".
	Errors []AppError `json:"errors" yaml:"errors" mapstructure:"errors"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Name corresponds to the JSON schema field "name".
	Name interface{} `json:"name" yaml:"name" mapstructure:"name"`
}

type ActionCreateFieldConfigData struct {
	// ActionName corresponds to the JSON schema field "actionName".
	ActionName interface{} `json:"actionName" yaml:"actionName" mapstructure:"actionName"`

	// ActionParams corresponds to the JSON schema field "actionParams".
	ActionParams ActionCreateFieldConfigDataActionParams `json:"actionParams" yaml:"actionParams" mapstructure:"actionParams"`
}

type ActionCreateFieldConfigDataActionParams struct {
	// CardConfigId corresponds to the JSON schema field "cardConfigId".
	CardConfigId DbId `json:"cardConfigId" yaml:"cardConfigId" mapstructure:"cardConfigId"`

	// FieldConfig corresponds to the JSON schema field "fieldConfig".
	FieldConfig FieldConfig `json:"fieldConfig" yaml:"fieldConfig" mapstructure:"fieldConfig"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ActionCreateFieldConfigDataActionParams) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["cardConfigId"]; raw != nil && !ok {
		return fmt.Errorf("field cardConfigId in ActionCreateFieldConfigDataActionParams: required")
	}
	if _, ok := raw["fieldConfig"]; raw != nil && !ok {
		return fmt.Errorf("field fieldConfig in ActionCreateFieldConfigDataActionParams: required")
	}
	type Plain ActionCreateFieldConfigDataActionParams
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = ActionCreateFieldConfigDataActionParams(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ActionCreateFieldConfigData) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["actionName"]; raw != nil && !ok {
		return fmt.Errorf("field actionName in ActionCreateFieldConfigData: required")
	}
	if _, ok := raw["actionParams"]; raw != nil && !ok {
		return fmt.Errorf("field actionParams in ActionCreateFieldConfigData: required")
	}
	type Plain ActionCreateFieldConfigData
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = ActionCreateFieldConfigData(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ActionCreateFieldConfig) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["authToken"]; raw != nil && !ok {
		return fmt.Errorf("field authToken in ActionCreateFieldConfig: required")
	}
	if _, ok := raw["data"]; raw != nil && !ok {
		return fmt.Errorf("field data in ActionCreateFieldConfig: required")
	}
	if _, ok := raw["errors"]; raw != nil && !ok {
		return fmt.Errorf("field errors in ActionCreateFieldConfig: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in ActionCreateFieldConfig: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in ActionCreateFieldConfig: required")
	}
	type Plain ActionCreateFieldConfig
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = ActionCreateFieldConfig(plain)
	return nil
}
