// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package genjsonschema

import "encoding/json"
import "fmt"
import "reflect"

type ActionName string

const ActionNameSignUpByEmail ActionName = "SignUpByEmail"

var enumValues_ActionName = []interface{}{
	"SignUpByEmail",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ActionName) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ActionName {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ActionName, v)
	}
	*j = ActionName(v)
	return nil
}
