// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package genjsonschema

import "encoding/json"
import "fmt"

type ActionSignUpByEmail struct {
	// AuthToken corresponds to the JSON schema field "authToken".
	AuthToken *string `json:"authToken" yaml:"authToken" mapstructure:"authToken"`

	// Data corresponds to the JSON schema field "data".
	Data ActionSignUpByEmailData `json:"data" yaml:"data" mapstructure:"data"`

	// Errors corresponds to the JSON schema field "errors".
	Errors []AppError `json:"errors" yaml:"errors" mapstructure:"errors"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Name corresponds to the JSON schema field "name".
	Name interface{} `json:"name" yaml:"name" mapstructure:"name"`
}

type ActionSignUpByEmailData struct {
	// ActionName corresponds to the JSON schema field "actionName".
	ActionName interface{} `json:"actionName" yaml:"actionName" mapstructure:"actionName"`

	// ActionParams corresponds to the JSON schema field "actionParams".
	ActionParams ActionSignUpByEmailDataActionParams `json:"actionParams" yaml:"actionParams" mapstructure:"actionParams"`
}

type ActionSignUpByEmailDataActionParams struct {
	// Email corresponds to the JSON schema field "email".
	Email string `json:"email" yaml:"email" mapstructure:"email"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ActionSignUpByEmailDataActionParams) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["email"]; raw != nil && !ok {
		return fmt.Errorf("field email in ActionSignUpByEmailDataActionParams: required")
	}
	type Plain ActionSignUpByEmailDataActionParams
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = ActionSignUpByEmailDataActionParams(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ActionSignUpByEmailData) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["actionName"]; raw != nil && !ok {
		return fmt.Errorf("field actionName in ActionSignUpByEmailData: required")
	}
	if _, ok := raw["actionParams"]; raw != nil && !ok {
		return fmt.Errorf("field actionParams in ActionSignUpByEmailData: required")
	}
	type Plain ActionSignUpByEmailData
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = ActionSignUpByEmailData(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ActionSignUpByEmail) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["authToken"]; raw != nil && !ok {
		return fmt.Errorf("field authToken in ActionSignUpByEmail: required")
	}
	if _, ok := raw["data"]; raw != nil && !ok {
		return fmt.Errorf("field data in ActionSignUpByEmail: required")
	}
	if _, ok := raw["errors"]; raw != nil && !ok {
		return fmt.Errorf("field errors in ActionSignUpByEmail: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in ActionSignUpByEmail: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in ActionSignUpByEmail: required")
	}
	type Plain ActionSignUpByEmail
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = ActionSignUpByEmail(plain)
	return nil
}
