// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package genjsonschema

import "encoding/json"
import "fmt"

type ActionSignUpByEmailCodeResponse struct {
	// AuthToken corresponds to the JSON schema field "authToken".
	AuthToken *string `json:"authToken" yaml:"authToken" mapstructure:"authToken"`

	// Data corresponds to the JSON schema field "data".
	Data ActionSignUpByEmailCodeResponseData `json:"data" yaml:"data" mapstructure:"data"`

	// Errors corresponds to the JSON schema field "errors".
	Errors []AppError `json:"errors" yaml:"errors" mapstructure:"errors"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Name corresponds to the JSON schema field "name".
	Name interface{} `json:"name" yaml:"name" mapstructure:"name"`

	// ResponseForId corresponds to the JSON schema field "responseForId".
	ResponseForId string `json:"responseForId" yaml:"responseForId" mapstructure:"responseForId"`
}

type ActionSignUpByEmailCodeResponseData struct {
	// ActionName corresponds to the JSON schema field "actionName".
	ActionName interface{} `json:"actionName" yaml:"actionName" mapstructure:"actionName"`

	// ActionParams corresponds to the JSON schema field "actionParams".
	ActionParams ActionSignUpByEmailCodeResponseDataActionParams `json:"actionParams" yaml:"actionParams" mapstructure:"actionParams"`
}

type ActionSignUpByEmailCodeResponseDataActionParams struct {
	// SessionToken corresponds to the JSON schema field "sessionToken".
	SessionToken string `json:"sessionToken" yaml:"sessionToken" mapstructure:"sessionToken"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ActionSignUpByEmailCodeResponseDataActionParams) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["sessionToken"]; raw != nil && !ok {
		return fmt.Errorf("field sessionToken in ActionSignUpByEmailCodeResponseDataActionParams: required")
	}
	type Plain ActionSignUpByEmailCodeResponseDataActionParams
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = ActionSignUpByEmailCodeResponseDataActionParams(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ActionSignUpByEmailCodeResponseData) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["actionName"]; raw != nil && !ok {
		return fmt.Errorf("field actionName in ActionSignUpByEmailCodeResponseData: required")
	}
	if _, ok := raw["actionParams"]; raw != nil && !ok {
		return fmt.Errorf("field actionParams in ActionSignUpByEmailCodeResponseData: required")
	}
	type Plain ActionSignUpByEmailCodeResponseData
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = ActionSignUpByEmailCodeResponseData(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ActionSignUpByEmailCodeResponse) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["authToken"]; raw != nil && !ok {
		return fmt.Errorf("field authToken in ActionSignUpByEmailCodeResponse: required")
	}
	if _, ok := raw["data"]; raw != nil && !ok {
		return fmt.Errorf("field data in ActionSignUpByEmailCodeResponse: required")
	}
	if _, ok := raw["errors"]; raw != nil && !ok {
		return fmt.Errorf("field errors in ActionSignUpByEmailCodeResponse: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in ActionSignUpByEmailCodeResponse: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in ActionSignUpByEmailCodeResponse: required")
	}
	if _, ok := raw["responseForId"]; raw != nil && !ok {
		return fmt.Errorf("field responseForId in ActionSignUpByEmailCodeResponse: required")
	}
	type Plain ActionSignUpByEmailCodeResponse
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = ActionSignUpByEmailCodeResponse(plain)
	return nil
}
