// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package genjsonschema

import "encoding/json"
import "fmt"

type AuthSession struct {
	// AuthToken corresponds to the JSON schema field "authToken".
	AuthToken string `json:"authToken" yaml:"authToken" mapstructure:"authToken"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AuthSession) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["authToken"]; raw != nil && !ok {
		return fmt.Errorf("field authToken in AuthSession: required")
	}
	type Plain AuthSession
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = AuthSession(plain)
	return nil
}
