// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package genjsonschema

import "encoding/json"
import "fmt"

type ChatOutputParseTextFromForeign struct {
	// Data corresponds to the JSON schema field "data".
	Data ChatOutputParseTextFromForeignData `json:"data" yaml:"data" mapstructure:"data"`

	// Errors corresponds to the JSON schema field "errors".
	Errors []ChatAiError `json:"errors" yaml:"errors" mapstructure:"errors"`
}

type ChatOutputParseTextFromForeignData interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ChatOutputParseTextFromForeign) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["data"]; !ok || v == nil {
		return fmt.Errorf("field data in ChatOutputParseTextFromForeign: required")
	}
	if v, ok := raw["errors"]; !ok || v == nil {
		return fmt.Errorf("field errors in ChatOutputParseTextFromForeign: required")
	}
	type Plain ChatOutputParseTextFromForeign
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = ChatOutputParseTextFromForeign(plain)
	return nil
}
