// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package genjsonschema

import "encoding/json"
import "fmt"

type LensQueryUser struct {
	// AuthToken corresponds to the JSON schema field "authToken".
	AuthToken *string `json:"authToken" yaml:"authToken" mapstructure:"authToken"`

	// Data corresponds to the JSON schema field "data".
	Data LensQueryUserData `json:"data" yaml:"data" mapstructure:"data"`

	// Errors corresponds to the JSON schema field "errors".
	Errors []AppError `json:"errors" yaml:"errors" mapstructure:"errors"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Name corresponds to the JSON schema field "name".
	Name interface{} `json:"name" yaml:"name" mapstructure:"name"`
}

type LensQueryUserData struct {
	// QueryName corresponds to the JSON schema field "queryName".
	QueryName interface{} `json:"queryName" yaml:"queryName" mapstructure:"queryName"`

	// QueryParams corresponds to the JSON schema field "queryParams".
	QueryParams LensQueryUserDataQueryParams `json:"queryParams" yaml:"queryParams" mapstructure:"queryParams"`
}

type LensQueryUserDataQueryParams map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LensQueryUserData) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["queryName"]; raw != nil && !ok {
		return fmt.Errorf("field queryName in LensQueryUserData: required")
	}
	if _, ok := raw["queryParams"]; raw != nil && !ok {
		return fmt.Errorf("field queryParams in LensQueryUserData: required")
	}
	type Plain LensQueryUserData
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = LensQueryUserData(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LensQueryUser) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["authToken"]; raw != nil && !ok {
		return fmt.Errorf("field authToken in LensQueryUser: required")
	}
	if _, ok := raw["data"]; raw != nil && !ok {
		return fmt.Errorf("field data in LensQueryUser: required")
	}
	if _, ok := raw["errors"]; raw != nil && !ok {
		return fmt.Errorf("field errors in LensQueryUser: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in LensQueryUser: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in LensQueryUser: required")
	}
	type Plain LensQueryUser
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = LensQueryUser(plain)
	return nil
}
