// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package genjsonschema

import "encoding/json"
import "fmt"

type LensQueryBase struct {
	// AuthToken corresponds to the JSON schema field "authToken".
	AuthToken *string `json:"authToken" yaml:"authToken" mapstructure:"authToken"`

	// Data corresponds to the JSON schema field "data".
	Data LensQueryBaseData `json:"data" yaml:"data" mapstructure:"data"`

	// Errors corresponds to the JSON schema field "errors".
	Errors []AppError `json:"errors" yaml:"errors" mapstructure:"errors"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Name corresponds to the JSON schema field "name".
	Name interface{} `json:"name" yaml:"name" mapstructure:"name"`

	// ResponseForId corresponds to the JSON schema field "responseForId".
	ResponseForId *string `json:"responseForId,omitempty" yaml:"responseForId,omitempty" mapstructure:"responseForId,omitempty"`
}

type LensQueryBaseData struct {
	// QueryName corresponds to the JSON schema field "queryName".
	QueryName LensQueryName `json:"queryName" yaml:"queryName" mapstructure:"queryName"`

	// QueryParams corresponds to the JSON schema field "queryParams".
	QueryParams LensQueryBaseDataQueryParams `json:"queryParams" yaml:"queryParams" mapstructure:"queryParams"`
}

type LensQueryBaseDataQueryParams map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LensQueryBaseData) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["queryName"]; raw != nil && !ok {
		return fmt.Errorf("field queryName in LensQueryBaseData: required")
	}
	if _, ok := raw["queryParams"]; raw != nil && !ok {
		return fmt.Errorf("field queryParams in LensQueryBaseData: required")
	}
	type Plain LensQueryBaseData
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = LensQueryBaseData(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LensQueryBase) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["authToken"]; raw != nil && !ok {
		return fmt.Errorf("field authToken in LensQueryBase: required")
	}
	if _, ok := raw["data"]; raw != nil && !ok {
		return fmt.Errorf("field data in LensQueryBase: required")
	}
	if _, ok := raw["errors"]; raw != nil && !ok {
		return fmt.Errorf("field errors in LensQueryBase: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in LensQueryBase: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in LensQueryBase: required")
	}
	type Plain LensQueryBase
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = LensQueryBase(plain)
	return nil
}
