// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package genjsonschema

import "encoding/json"
import "fmt"

type LensUserResponse struct {
	// AuthToken corresponds to the JSON schema field "authToken".
	AuthToken *string `json:"authToken" yaml:"authToken" mapstructure:"authToken"`

	// Data corresponds to the JSON schema field "data".
	Data LensUserResponseData `json:"data" yaml:"data" mapstructure:"data"`

	// Errors corresponds to the JSON schema field "errors".
	Errors []AppError `json:"errors" yaml:"errors" mapstructure:"errors"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Name corresponds to the JSON schema field "name".
	Name interface{} `json:"name" yaml:"name" mapstructure:"name"`

	// ResponseForId corresponds to the JSON schema field "responseForId".
	ResponseForId string `json:"responseForId" yaml:"responseForId" mapstructure:"responseForId"`
}

type LensUserResponseData struct {
	// QueryName corresponds to the JSON schema field "queryName".
	QueryName interface{} `json:"queryName" yaml:"queryName" mapstructure:"queryName"`

	// QueryParams corresponds to the JSON schema field "queryParams".
	QueryParams LensUserResponseDataQueryParams `json:"queryParams" yaml:"queryParams" mapstructure:"queryParams"`
}

type LensUserResponseDataQueryParams struct {
	// User corresponds to the JSON schema field "user".
	User User `json:"user" yaml:"user" mapstructure:"user"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LensUserResponseDataQueryParams) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["user"]; raw != nil && !ok {
		return fmt.Errorf("field user in LensUserResponseDataQueryParams: required")
	}
	type Plain LensUserResponseDataQueryParams
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = LensUserResponseDataQueryParams(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LensUserResponseData) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["queryName"]; raw != nil && !ok {
		return fmt.Errorf("field queryName in LensUserResponseData: required")
	}
	if _, ok := raw["queryParams"]; raw != nil && !ok {
		return fmt.Errorf("field queryParams in LensUserResponseData: required")
	}
	type Plain LensUserResponseData
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = LensUserResponseData(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LensUserResponse) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["authToken"]; raw != nil && !ok {
		return fmt.Errorf("field authToken in LensUserResponse: required")
	}
	if _, ok := raw["data"]; raw != nil && !ok {
		return fmt.Errorf("field data in LensUserResponse: required")
	}
	if _, ok := raw["errors"]; raw != nil && !ok {
		return fmt.Errorf("field errors in LensUserResponse: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in LensUserResponse: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in LensUserResponse: required")
	}
	if _, ok := raw["responseForId"]; raw != nil && !ok {
		return fmt.Errorf("field responseForId in LensUserResponse: required")
	}
	type Plain LensUserResponse
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = LensUserResponse(plain)
	return nil
}
