// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package genjsonschema

import "encoding/json"
import "fmt"

// CardConfig with its fieldConfigs loaded
type LensCardConfig struct {
	// FieldConfigs corresponds to the JSON schema field "fieldConfigs".
	FieldConfigs []FieldConfig `json:"fieldConfigs" yaml:"fieldConfigs" mapstructure:"fieldConfigs"`

	// The name of the card config
	Name string `json:"name" yaml:"name" mapstructure:"name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LensCardConfig) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["fieldConfigs"]; raw != nil && !ok {
		return fmt.Errorf("field fieldConfigs in LensCardConfig: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in LensCardConfig: required")
	}
	type Plain LensCardConfig
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = LensCardConfig(plain)
	return nil
}
