// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package genjsonschema

import "encoding/json"
import "fmt"

type LensQueryUserCardConfigsResponse struct {
	// AuthToken corresponds to the JSON schema field "authToken".
	AuthToken *string `json:"authToken" yaml:"authToken" mapstructure:"authToken"`

	// Data corresponds to the JSON schema field "data".
	Data LensQueryUserCardConfigsResponseData `json:"data" yaml:"data" mapstructure:"data"`

	// Errors corresponds to the JSON schema field "errors".
	Errors []AppError `json:"errors" yaml:"errors" mapstructure:"errors"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Name corresponds to the JSON schema field "name".
	Name interface{} `json:"name" yaml:"name" mapstructure:"name"`

	// ResponseForId corresponds to the JSON schema field "responseForId".
	ResponseForId string `json:"responseForId" yaml:"responseForId" mapstructure:"responseForId"`
}

type LensQueryUserCardConfigsResponseData struct {
	// QueryName corresponds to the JSON schema field "queryName".
	QueryName interface{} `json:"queryName" yaml:"queryName" mapstructure:"queryName"`

	// QueryParams corresponds to the JSON schema field "queryParams".
	QueryParams LensQueryUserCardConfigsResponseDataQueryParams `json:"queryParams" yaml:"queryParams" mapstructure:"queryParams"`
}

type LensQueryUserCardConfigsResponseDataQueryParams struct {
	// CardConfigs corresponds to the JSON schema field "cardConfigs".
	CardConfigs []CardConfig `json:"cardConfigs" yaml:"cardConfigs" mapstructure:"cardConfigs"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LensQueryUserCardConfigsResponseDataQueryParams) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["cardConfigs"]; raw != nil && !ok {
		return fmt.Errorf("field cardConfigs in LensQueryUserCardConfigsResponseDataQueryParams: required")
	}
	type Plain LensQueryUserCardConfigsResponseDataQueryParams
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = LensQueryUserCardConfigsResponseDataQueryParams(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LensQueryUserCardConfigsResponseData) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["queryName"]; raw != nil && !ok {
		return fmt.Errorf("field queryName in LensQueryUserCardConfigsResponseData: required")
	}
	if _, ok := raw["queryParams"]; raw != nil && !ok {
		return fmt.Errorf("field queryParams in LensQueryUserCardConfigsResponseData: required")
	}
	type Plain LensQueryUserCardConfigsResponseData
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = LensQueryUserCardConfigsResponseData(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LensQueryUserCardConfigsResponse) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["authToken"]; raw != nil && !ok {
		return fmt.Errorf("field authToken in LensQueryUserCardConfigsResponse: required")
	}
	if _, ok := raw["data"]; raw != nil && !ok {
		return fmt.Errorf("field data in LensQueryUserCardConfigsResponse: required")
	}
	if _, ok := raw["errors"]; raw != nil && !ok {
		return fmt.Errorf("field errors in LensQueryUserCardConfigsResponse: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in LensQueryUserCardConfigsResponse: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in LensQueryUserCardConfigsResponse: required")
	}
	if _, ok := raw["responseForId"]; raw != nil && !ok {
		return fmt.Errorf("field responseForId in LensQueryUserCardConfigsResponse: required")
	}
	type Plain LensQueryUserCardConfigsResponse
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = LensQueryUserCardConfigsResponse(plain)
	return nil
}
