// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package genjsonschema

import "encoding/json"
import "fmt"

type LensModels struct {
	// ModelBase corresponds to the JSON schema field "ModelBase".
	ModelBase LensModelBase `json:"ModelBase" yaml:"ModelBase" mapstructure:"ModelBase"`

	// SessionToken corresponds to the JSON schema field "SessionToken".
	SessionToken SessionToken `json:"SessionToken" yaml:"SessionToken" mapstructure:"SessionToken"`

	// SignUpCode corresponds to the JSON schema field "SignUpCode".
	SignUpCode SignUpCode `json:"SignUpCode" yaml:"SignUpCode" mapstructure:"SignUpCode"`

	// User corresponds to the JSON schema field "User".
	User User `json:"User" yaml:"User" mapstructure:"User"`

	// UserSettings corresponds to the JSON schema field "UserSettings".
	UserSettings UserSettings `json:"UserSettings" yaml:"UserSettings" mapstructure:"UserSettings"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LensModels) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["ModelBase"]; raw != nil && !ok {
		return fmt.Errorf("field ModelBase in LensModels: required")
	}
	if _, ok := raw["SessionToken"]; raw != nil && !ok {
		return fmt.Errorf("field SessionToken in LensModels: required")
	}
	if _, ok := raw["SignUpCode"]; raw != nil && !ok {
		return fmt.Errorf("field SignUpCode in LensModels: required")
	}
	if _, ok := raw["User"]; raw != nil && !ok {
		return fmt.Errorf("field User in LensModels: required")
	}
	if _, ok := raw["UserSettings"]; raw != nil && !ok {
		return fmt.Errorf("field UserSettings in LensModels: required")
	}
	type Plain LensModels
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = LensModels(plain)
	return nil
}
