// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package genjsonschema

import "encoding/json"
import "fmt"

type LensQueryCardConfigResponse struct {
	// AuthToken corresponds to the JSON schema field "authToken".
	AuthToken *string `json:"authToken" yaml:"authToken" mapstructure:"authToken"`

	// Data corresponds to the JSON schema field "data".
	Data LensQueryCardConfigResponseData `json:"data" yaml:"data" mapstructure:"data"`

	// Errors corresponds to the JSON schema field "errors".
	Errors []AppError `json:"errors" yaml:"errors" mapstructure:"errors"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Name corresponds to the JSON schema field "name".
	Name interface{} `json:"name" yaml:"name" mapstructure:"name"`

	// ResponseForId corresponds to the JSON schema field "responseForId".
	ResponseForId string `json:"responseForId" yaml:"responseForId" mapstructure:"responseForId"`
}

type LensQueryCardConfigResponseData struct {
	// QueryName corresponds to the JSON schema field "queryName".
	QueryName interface{} `json:"queryName" yaml:"queryName" mapstructure:"queryName"`

	// QueryParams corresponds to the JSON schema field "queryParams".
	QueryParams LensQueryCardConfigResponseDataQueryParams `json:"queryParams" yaml:"queryParams" mapstructure:"queryParams"`
}

type LensQueryCardConfigResponseDataQueryParams struct {
	// CardConfig corresponds to the JSON schema field "cardConfig".
	CardConfig LensCardConfig `json:"cardConfig" yaml:"cardConfig" mapstructure:"cardConfig"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LensQueryCardConfigResponseDataQueryParams) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["cardConfig"]; raw != nil && !ok {
		return fmt.Errorf("field cardConfig in LensQueryCardConfigResponseDataQueryParams: required")
	}
	type Plain LensQueryCardConfigResponseDataQueryParams
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = LensQueryCardConfigResponseDataQueryParams(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LensQueryCardConfigResponseData) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["queryName"]; raw != nil && !ok {
		return fmt.Errorf("field queryName in LensQueryCardConfigResponseData: required")
	}
	if _, ok := raw["queryParams"]; raw != nil && !ok {
		return fmt.Errorf("field queryParams in LensQueryCardConfigResponseData: required")
	}
	type Plain LensQueryCardConfigResponseData
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = LensQueryCardConfigResponseData(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LensQueryCardConfigResponse) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["authToken"]; raw != nil && !ok {
		return fmt.Errorf("field authToken in LensQueryCardConfigResponse: required")
	}
	if _, ok := raw["data"]; raw != nil && !ok {
		return fmt.Errorf("field data in LensQueryCardConfigResponse: required")
	}
	if _, ok := raw["errors"]; raw != nil && !ok {
		return fmt.Errorf("field errors in LensQueryCardConfigResponse: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in LensQueryCardConfigResponse: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in LensQueryCardConfigResponse: required")
	}
	if _, ok := raw["responseForId"]; raw != nil && !ok {
		return fmt.Errorf("field responseForId in LensQueryCardConfigResponse: required")
	}
	type Plain LensQueryCardConfigResponse
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = LensQueryCardConfigResponse(plain)
	return nil
}
