// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package genjsonschema

type GenJsonSchema struct {
	// Model corresponds to the JSON schema field "model".
	Model *Models `json:"model,omitempty" yaml:"model,omitempty" mapstructure:"model,omitempty"`
}

type MessageMap struct {
	// ParseTextFromForeign corresponds to the JSON schema field
	// "ParseTextFromForeign".
	ParseTextFromForeign *MessageParseTextFromForeign `json:"ParseTextFromForeign,omitempty" yaml:"ParseTextFromForeign,omitempty" mapstructure:"ParseTextFromForeign,omitempty"`
}

type Models struct {
	// MessageBase corresponds to the JSON schema field "MessageBase".
	MessageBase *MessageBase `json:"MessageBase,omitempty" yaml:"MessageBase,omitempty" mapstructure:"MessageBase,omitempty"`

	// Messages corresponds to the JSON schema field "messages".
	Messages *MessageMap `json:"messages,omitempty" yaml:"messages,omitempty" mapstructure:"messages,omitempty"`
}
