// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package genjsonschema

import "encoding/json"
import "fmt"
import "reflect"

type MessageParseTextFromForeign struct {
	// Input corresponds to the JSON schema field "input".
	Input MessageParseTextFromForeignInput `json:"input" yaml:"input" mapstructure:"input"`

	// Output corresponds to the JSON schema field "output".
	Output MessageParseTextFromForeignOutput `json:"output" yaml:"output" mapstructure:"output"`
}

type MessageParseTextFromForeignInput struct {
	// Data corresponds to the JSON schema field "data".
	Data MessageParseTextFromForeignInputData `json:"data" yaml:"data" mapstructure:"data"`

	// Id corresponds to the JSON schema field "id".
	Id Id `json:"id" yaml:"id" mapstructure:"id"`

	// Name corresponds to the JSON schema field "name".
	Name MessageParseTextFromForeignInputName `json:"name" yaml:"name" mapstructure:"name"`
}

type MessageParseTextFromForeignInputData struct {
	// OriginalLanguages corresponds to the JSON schema field "originalLanguages".
	OriginalLanguages ForeignLanguages `json:"originalLanguages" yaml:"originalLanguages" mapstructure:"originalLanguages"`

	// Text corresponds to the JSON schema field "text".
	Text string `json:"text" yaml:"text" mapstructure:"text"`

	// TranslationLanguage corresponds to the JSON schema field "translationLanguage".
	TranslationLanguage TranslationLanguage `json:"translationLanguage" yaml:"translationLanguage" mapstructure:"translationLanguage"`
}

type MessageParseTextFromForeignInputName string

const MessageParseTextFromForeignInputNameParseTextFromForeign MessageParseTextFromForeignInputName = "ParseTextFromForeign"

type MessageParseTextFromForeignOutput struct {
	// Data corresponds to the JSON schema field "data".
	Data ChatOutputDataParseTextFromForeign `json:"data" yaml:"data" mapstructure:"data"`

	// Errors corresponds to the JSON schema field "errors".
	Errors []AppError `json:"errors" yaml:"errors" mapstructure:"errors"`

	// Id corresponds to the JSON schema field "id".
	Id Id `json:"id" yaml:"id" mapstructure:"id"`

	// Name corresponds to the JSON schema field "name".
	Name MessageParseTextFromForeignOutputName `json:"name" yaml:"name" mapstructure:"name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MessageParseTextFromForeignInputName) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_MessageParseTextFromForeignInputName {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_MessageParseTextFromForeignInputName, v)
	}
	*j = MessageParseTextFromForeignInputName(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MessageParseTextFromForeignInput) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["data"]; !ok || v == nil {
		return fmt.Errorf("field data in MessageParseTextFromForeignInput: required")
	}
	if v, ok := raw["id"]; !ok || v == nil {
		return fmt.Errorf("field id in MessageParseTextFromForeignInput: required")
	}
	if v, ok := raw["name"]; !ok || v == nil {
		return fmt.Errorf("field name in MessageParseTextFromForeignInput: required")
	}
	type Plain MessageParseTextFromForeignInput
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = MessageParseTextFromForeignInput(plain)
	return nil
}

type MessageParseTextFromForeignOutputName string

var enumValues_MessageParseTextFromForeignOutputName = []interface{}{
	"ParseTextFromForeign",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MessageParseTextFromForeignOutputName) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_MessageParseTextFromForeignOutputName {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_MessageParseTextFromForeignOutputName, v)
	}
	*j = MessageParseTextFromForeignOutputName(v)
	return nil
}

const MessageParseTextFromForeignOutputNameParseTextFromForeign MessageParseTextFromForeignOutputName = "ParseTextFromForeign"

var enumValues_MessageParseTextFromForeignInputName = []interface{}{
	"ParseTextFromForeign",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MessageParseTextFromForeignOutput) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["data"]; !ok || v == nil {
		return fmt.Errorf("field data in MessageParseTextFromForeignOutput: required")
	}
	if v, ok := raw["errors"]; !ok || v == nil {
		return fmt.Errorf("field errors in MessageParseTextFromForeignOutput: required")
	}
	if v, ok := raw["id"]; !ok || v == nil {
		return fmt.Errorf("field id in MessageParseTextFromForeignOutput: required")
	}
	if v, ok := raw["name"]; !ok || v == nil {
		return fmt.Errorf("field name in MessageParseTextFromForeignOutput: required")
	}
	type Plain MessageParseTextFromForeignOutput
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = MessageParseTextFromForeignOutput(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MessageParseTextFromForeignInputData) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["originalLanguages"]; !ok || v == nil {
		return fmt.Errorf("field originalLanguages in MessageParseTextFromForeignInputData: required")
	}
	if v, ok := raw["text"]; !ok || v == nil {
		return fmt.Errorf("field text in MessageParseTextFromForeignInputData: required")
	}
	if v, ok := raw["translationLanguage"]; !ok || v == nil {
		return fmt.Errorf("field translationLanguage in MessageParseTextFromForeignInputData: required")
	}
	type Plain MessageParseTextFromForeignInputData
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = MessageParseTextFromForeignInputData(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MessageParseTextFromForeign) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["input"]; !ok || v == nil {
		return fmt.Errorf("field input in MessageParseTextFromForeign: required")
	}
	if v, ok := raw["output"]; !ok || v == nil {
		return fmt.Errorf("field output in MessageParseTextFromForeign: required")
	}
	type Plain MessageParseTextFromForeign
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = MessageParseTextFromForeign(plain)
	return nil
}
