// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package genjsonschema

import "encoding/json"
import "fmt"
import "reflect"

type MessageDefineTerm struct {
	// Input corresponds to the JSON schema field "input".
	Input MessageDefineTermInput `json:"input" yaml:"input" mapstructure:"input"`

	// Output corresponds to the JSON schema field "output".
	Output MessageDefineTermOutput `json:"output" yaml:"output" mapstructure:"output"`
}

type MessageDefineTermInput struct {
	// AuthToken corresponds to the JSON schema field "authToken".
	AuthToken *string `json:"authToken,omitempty" yaml:"authToken,omitempty" mapstructure:"authToken,omitempty"`

	// Data corresponds to the JSON schema field "data".
	Data MessageDefineTermInputData `json:"data" yaml:"data" mapstructure:"data"`

	// Id corresponds to the JSON schema field "id".
	Id *Id `json:"id,omitempty" yaml:"id,omitempty" mapstructure:"id,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name MessageDefineTermInputName `json:"name" yaml:"name" mapstructure:"name"`
}

type MessageDefineTermInputData struct {
	// ChatInput corresponds to the JSON schema field "chatInput".
	ChatInput ChatInputDefineTerm `json:"chatInput" yaml:"chatInput" mapstructure:"chatInput"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MessageDefineTermInputData) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["chatInput"]; raw != nil && !ok {
		return fmt.Errorf("field chatInput in MessageDefineTermInputData: required")
	}
	type Plain MessageDefineTermInputData
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = MessageDefineTermInputData(plain)
	return nil
}

type MessageDefineTermInputName string

const MessageDefineTermInputNameDefineTerm MessageDefineTermInputName = "DefineTerm"

var enumValues_MessageDefineTermInputName = []interface{}{
	"DefineTerm",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MessageDefineTermInputName) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_MessageDefineTermInputName {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_MessageDefineTermInputName, v)
	}
	*j = MessageDefineTermInputName(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MessageDefineTermInput) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["data"]; raw != nil && !ok {
		return fmt.Errorf("field data in MessageDefineTermInput: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in MessageDefineTermInput: required")
	}
	type Plain MessageDefineTermInput
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = MessageDefineTermInput(plain)
	return nil
}

type MessageDefineTermOutput struct {
	// Data corresponds to the JSON schema field "data".
	Data *MessageDefineTermOutputData `json:"data,omitempty" yaml:"data,omitempty" mapstructure:"data,omitempty"`

	// Errors corresponds to the JSON schema field "errors".
	Errors []AppError `json:"errors" yaml:"errors" mapstructure:"errors"`

	// Id corresponds to the JSON schema field "id".
	Id Id `json:"id" yaml:"id" mapstructure:"id"`

	// Name corresponds to the JSON schema field "name".
	Name MessageDefineTermOutputName `json:"name" yaml:"name" mapstructure:"name"`
}

type MessageDefineTermOutputData struct {
	// Decks corresponds to the JSON schema field "decks".
	Decks []Deck `json:"decks" yaml:"decks" mapstructure:"decks"`

	// Definition corresponds to the JSON schema field "definition".
	Definition Definition `json:"definition" yaml:"definition" mapstructure:"definition"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MessageDefineTermOutputData) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["decks"]; raw != nil && !ok {
		return fmt.Errorf("field decks in MessageDefineTermOutputData: required")
	}
	if _, ok := raw["definition"]; raw != nil && !ok {
		return fmt.Errorf("field definition in MessageDefineTermOutputData: required")
	}
	type Plain MessageDefineTermOutputData
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = MessageDefineTermOutputData(plain)
	return nil
}

type MessageDefineTermOutputName string

const MessageDefineTermOutputNameDefineTerm MessageDefineTermOutputName = "DefineTerm"

var enumValues_MessageDefineTermOutputName = []interface{}{
	"DefineTerm",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MessageDefineTermOutputName) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_MessageDefineTermOutputName {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_MessageDefineTermOutputName, v)
	}
	*j = MessageDefineTermOutputName(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MessageDefineTermOutput) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["errors"]; raw != nil && !ok {
		return fmt.Errorf("field errors in MessageDefineTermOutput: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in MessageDefineTermOutput: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in MessageDefineTermOutput: required")
	}
	type Plain MessageDefineTermOutput
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = MessageDefineTermOutput(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MessageDefineTerm) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["input"]; raw != nil && !ok {
		return fmt.Errorf("field input in MessageDefineTerm: required")
	}
	if _, ok := raw["output"]; raw != nil && !ok {
		return fmt.Errorf("field output in MessageDefineTerm: required")
	}
	type Plain MessageDefineTerm
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = MessageDefineTerm(plain)
	return nil
}
