// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package genjsonschema

import "encoding/json"
import "fmt"
import "reflect"

type WsMessageNameRequestToServer string

const WsMessageNameRequestToServerAction WsMessageNameRequestToServer = "Action"
const WsMessageNameRequestToServerLenseQuery WsMessageNameRequestToServer = "LenseQuery"

var enumValues_WsMessageNameRequestToServer = []interface{}{
	"LenseQuery",
	"Action",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *WsMessageNameRequestToServer) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_WsMessageNameRequestToServer {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_WsMessageNameRequestToServer, v)
	}
	*j = WsMessageNameRequestToServer(v)
	return nil
}
