// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package genjsonschema

import "encoding/json"
import "fmt"
import "reflect"

type WsMessageNameEventToServer string

const WsMessageNameEventToServerMutation WsMessageNameEventToServer = "Mutation"

var enumValues_WsMessageNameEventToServer = []interface{}{
	"Mutation",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *WsMessageNameEventToServer) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_WsMessageNameEventToServer {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_WsMessageNameEventToServer, v)
	}
	*j = WsMessageNameEventToServer(v)
	return nil
}
