// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package genjsonschema

import "encoding/json"
import "fmt"
import "reflect"

type WsMessageType string

const WsMessageTypeEventFromServer WsMessageType = "EventFromServer"
const WsMessageTypeEventToServer WsMessageType = "EventToServer"
const WsMessageTypeQueryFromServer WsMessageType = "QueryFromServer"
const WsMessageTypeQueryToServer WsMessageType = "QueryToServer"

var enumValues_WsMessageType = []interface{}{
	"QueryToServer",
	"QueryFromServer",
	"EventToServer",
	"EventFromServer",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *WsMessageType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_WsMessageType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_WsMessageType, v)
	}
	*j = WsMessageType(v)
	return nil
}
