// Code generated by qtc from "FieldPromptUser.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:1
package tempfieldprompt

//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:1
import "api-go/pkg/genjsonschema"

//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:3
type FieldPromptUserProps struct {
	CardConfig       genjsonschema.CardConfig
	FieldConfig      genjsonschema.FieldConfig
	CardParamValues  map[string]string
	FieldParamValues map[string]string
}

//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:11
func StreamFieldPromptUser(qw422016 *qt422016.Writer, props FieldPromptUserProps) {
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:11
	qw422016.N().S(`
=== CARD CONFIG (Context) ===
- Card Name: `)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:13
	qw422016.N().S(props.CardConfig.Name)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:13
	qw422016.N().S(`
- Card Prompt (Context Only): `)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:14
	qw422016.N().S(props.CardConfig.Prompt)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:14
	qw422016.N().S(`

=== PARAMETERS DEFINITIONS ===
`)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:17
	for _, parameterDefinition := range props.CardConfig.PromptParameterDefinitions {
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:17
		qw422016.N().S(`
- Name: `)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:18
		qw422016.N().S(parameterDefinition.Name)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:18
		qw422016.N().S(`
  Description: `)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:19
		qw422016.N().S(parameterDefinition.ParameterDescription)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:19
		qw422016.N().S(`
`)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:20
	}
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:20
	qw422016.N().S(`
`)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:21
	for _, parameterDefinition := range props.FieldConfig.PromptParameterDefinitions {
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:21
		qw422016.N().S(`
- Name: `)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:22
		qw422016.N().S(parameterDefinition.Name)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:22
		qw422016.N().S(`
  Description: `)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:23
		qw422016.N().S(parameterDefinition.ParameterDescription)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:23
		qw422016.N().S(`
`)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:24
	}
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:24
	qw422016.N().S(`

=== FIELD CONFIG (Instructions) ===
- Field Name: `)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:27
	qw422016.N().S(props.FieldConfig.Name)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:27
	qw422016.N().S(`
- Field Prompt (AI Instructions): `)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:28
	qw422016.N().S(props.FieldConfig.Prompt)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:28
	qw422016.N().S(`

=== PARAMETERS VALUES ===
`)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:31
	for _, parameterDefinition := range props.CardConfig.PromptParameterDefinitions {
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:31
		qw422016.N().S(`
- Name: `)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:32
		qw422016.N().S(parameterDefinition.Name)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:32
		qw422016.N().S(`
  Value: `)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:33
		qw422016.N().S(props.CardParamValues[parameterDefinition.Name])
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:33
		qw422016.N().S(`
`)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:34
	}
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:34
	qw422016.N().S(`
`)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:35
	for _, parameterDefinition := range props.FieldConfig.PromptParameterDefinitions {
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:35
		qw422016.N().S(`
- Name: `)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:36
		qw422016.N().S(parameterDefinition.Name)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:36
		qw422016.N().S(`
  Value: `)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:37
		qw422016.N().S(props.FieldParamValues[parameterDefinition.Name])
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:37
		qw422016.N().S(`
`)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:38
	}
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:38
	qw422016.N().S(`

=== USER REQUEST ===
1. Use the Card Prompt above solely as context or background.
2. Follow the Field Prompt as your main instructions for generating the final text response.
3. Incorporate the parameter definitions and use the provided parameter values as applicable.
4. Produce your answer in plain text.
`)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:45
}

//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:45
func WriteFieldPromptUser(qq422016 qtio422016.Writer, props FieldPromptUserProps) {
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:45
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:45
	StreamFieldPromptUser(qw422016, props)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:45
	qt422016.ReleaseWriter(qw422016)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:45
}

//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:45
func FieldPromptUser(props FieldPromptUserProps) string {
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:45
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:45
	WriteFieldPromptUser(qb422016, props)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:45
	qs422016 := string(qb422016.B)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:45
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:45
	return qs422016
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:45
}
