// Code generated by qtc from "FieldPromptUser.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:1
package tempfieldprompt

//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:1
import "api-go/pkg/genjsonschema"

//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:3
type FieldPromptUserProps struct {
	CardConfigJsonSchema       string
	PromptParameterDefinitions []genjsonschema.PromptParameterDefinition
	CardParamValues            map[string]string
}

//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:10
func StreamFieldPromptUser(qw422016 *qt422016.Writer, props FieldPromptUserProps) {
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:10
	qw422016.N().S(`
You are a stateless software function named `)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:10
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:10
	qw422016.N().S(`GenerateJsonObject`)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:10
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:10
	qw422016.N().S(`.
Your input parameters:
`)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:10
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:10
	qw422016.N().S(``)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:10
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:10
	qw422016.N().S(``)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:10
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:10
	qw422016.N().S(`json
[
`)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:15
	for _, parameterDefinition := range props.PromptParameterDefinitions {
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:15
		qw422016.N().S(`  {
    "name": "`)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:17
		qw422016.N().S(parameterDefinition.Name)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:17
		qw422016.N().S(`",
    "description": "`)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:18
		qw422016.N().S(parameterDefinition.ParameterDescription)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:18
		qw422016.N().S(`",
    "value": "`)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:19
		qw422016.N().S(props.CardParamValues[parameterDefinition.Name])
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:19
		qw422016.N().S(`"
  },
`)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:21
	}
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:21
	qw422016.N().S(`  {
    "name": "targetJsonSchema",
    "description": "The JSON schema of the object to be generated",
    "value": `)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:25
	qw422016.N().S(props.CardConfigJsonSchema)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:25
	qw422016.N().S(`
  }
]
`)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:25
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:25
	qw422016.N().S(``)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:25
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:25
	qw422016.N().S(``)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:25
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:25
	qw422016.N().S(`

The purpose of this function is to generate a JSON object that fits the JSON schema described by the `)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:25
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:25
	qw422016.N().S(`targetJsonSchema`)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:25
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:25
	qw422016.N().S(` parameter to the best of your ability.

Return **only** a single, JSON object that validates against the `)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:25
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:25
	qw422016.N().S(`targetJsonSchema`)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:25
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:25
	qw422016.N().S(` parameter.
`)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:33
}

//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:33
func WriteFieldPromptUser(qq422016 qtio422016.Writer, props FieldPromptUserProps) {
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:33
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:33
	StreamFieldPromptUser(qw422016, props)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:33
	qt422016.ReleaseWriter(qw422016)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:33
}

//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:33
func FieldPromptUser(props FieldPromptUserProps) string {
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:33
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:33
	WriteFieldPromptUser(qb422016, props)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:33
	qs422016 := string(qb422016.B)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:33
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:33
	return qs422016
//line ../../pkg/tempfieldprompt/FieldPromptUser.qtpl:33
}
