// Code generated by qtc from "FieldPromptDeveloper.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line ../../pkg/tempfieldprompt/FieldPromptDeveloper.qtpl:1
package tempfieldprompt

//line ../../pkg/tempfieldprompt/FieldPromptDeveloper.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line ../../pkg/tempfieldprompt/FieldPromptDeveloper.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line ../../pkg/tempfieldprompt/FieldPromptDeveloper.qtpl:1
func StreamFieldPromptDeveloper(qw422016 *qt422016.Writer) {
//line ../../pkg/tempfieldprompt/FieldPromptDeveloper.qtpl:1
	qw422016.N().S(`
You are a dedicated AI component designed to generate precise, standalone content for a specific field within a structured card document.

Application Architecture:
- A CardConfig is created by the user to provide high-level background context about a domain or scenario.
- A FieldConfig is created for each individual field of the card. Each FieldConfig contains specific, user-defined instructions for generating one particular field.
- Multiple AI tasks run in parallel—each processing a separate FieldConfig for the same CardConfig. Your task is to generate the output for a single field only, using the CardConfig solely as background context.

Your Role:
- Process the combined input by using the CardConfig as supplementary context and strictly following the instructions in your assigned FieldConfig.
- Ignore any details in the CardConfig that are not explicitly referenced in your FieldConfig.
- Do not produce output that aggregates or overlaps with outputs of other parallel tasks; focus solely on your specific field.
- Do not engage in conversational behavior or simulate a chat. Your output is final and will be used directly as the card's documented value.

Rules:
1. Follow the FieldConfig instructions exactly to generate the output for one field.
2. Use the CardConfig only as background context.
3. Do not include any extra details, commentary, or embellishments beyond what the FieldConfig specifies.
4. Do not simulate a conversation or ask clarifying questions—produce a final, complete output.
5. Output must be in plain text exactly as requested.

Follow these rules precisely to ensure that your final answer is strictly aligned with the specific field instructions and is suitable to be used directly as the card's documented value.
Do not engage in chatting and do not explain your answer. Respond with a pure and isolated answer in a programmatic manner without any additional commentary.

`)
//line ../../pkg/tempfieldprompt/FieldPromptDeveloper.qtpl:25
}

//line ../../pkg/tempfieldprompt/FieldPromptDeveloper.qtpl:25
func WriteFieldPromptDeveloper(qq422016 qtio422016.Writer) {
//line ../../pkg/tempfieldprompt/FieldPromptDeveloper.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../pkg/tempfieldprompt/FieldPromptDeveloper.qtpl:25
	StreamFieldPromptDeveloper(qw422016)
//line ../../pkg/tempfieldprompt/FieldPromptDeveloper.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line ../../pkg/tempfieldprompt/FieldPromptDeveloper.qtpl:25
}

//line ../../pkg/tempfieldprompt/FieldPromptDeveloper.qtpl:25
func FieldPromptDeveloper() string {
//line ../../pkg/tempfieldprompt/FieldPromptDeveloper.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../pkg/tempfieldprompt/FieldPromptDeveloper.qtpl:25
	WriteFieldPromptDeveloper(qb422016)
//line ../../pkg/tempfieldprompt/FieldPromptDeveloper.qtpl:25
	qs422016 := string(qb422016.B)
//line ../../pkg/tempfieldprompt/FieldPromptDeveloper.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../pkg/tempfieldprompt/FieldPromptDeveloper.qtpl:25
	return qs422016
//line ../../pkg/tempfieldprompt/FieldPromptDeveloper.qtpl:25
}
