// Code generated by qtc from "GenerateDictionaryEntry.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:1
package tempfieldprompt

//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:1
import "api-go/pkg/genjsonschema"

//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:3
type GenerateDictionaryEntryProps struct {
	CardConfigJsonSchema       string
	PromptParameterDefinitions []genjsonschema.PromptParameterDefinition
	CardParamValues            map[string]string
}

//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:10
func StreamGenerateDictionaryEntry(qw422016 *qt422016.Writer, props GenerateDictionaryEntryProps) {
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:10
	qw422016.N().S(`
You are a stateless software function named `)
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:10
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:10
	qw422016.N().S(`GenerateDictionaryEntry`)
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:10
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:10
	qw422016.N().S(`.
Your input parameters:
`)
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:10
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:10
	qw422016.N().S(``)
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:10
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:10
	qw422016.N().S(``)
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:10
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:10
	qw422016.N().S(`json
[
`)
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:15
	for _, parameterDefinition := range props.PromptParameterDefinitions {
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:15
		qw422016.N().S(`  {
    "name": "`)
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:17
		qw422016.N().S(parameterDefinition.Name)
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:17
		qw422016.N().S(`",
    "description": "`)
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:18
		qw422016.N().S(parameterDefinition.ParameterDescription)
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:18
		qw422016.N().S(`",
    "value": "`)
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:19
		qw422016.N().S(props.CardParamValues[parameterDefinition.Name])
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:19
		qw422016.N().S(`"
  },
`)
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:21
	}
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:21
	qw422016.N().S(`]
`)
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:21
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:21
	qw422016.N().S(``)
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:21
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:21
	qw422016.N().S(``)
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:21
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:21
	qw422016.N().S(`

The purpose of this function is to generate a JSON object that fits the JSON schema of the dictionary enty described by the `)
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:21
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:21
	qw422016.N().S(`targetJsonSchema`)
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:21
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:21
	qw422016.N().S(` parameter to the best of your ability.
- The definition entry should strive for the best dictionary level of quality and accuracy.
- The definition should include as many meanings as possible, including rare usages and folklore.

Return **only** a single, JSON object matching this schema:
`)
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:21
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:21
	qw422016.N().S(``)
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:21
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:21
	qw422016.N().S(``)
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:21
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:21
	qw422016.N().S(`json
`)
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:31
	qw422016.N().S(props.CardConfigJsonSchema)
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:31
	qw422016.N().S(`
`)
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:31
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:31
	qw422016.N().S(``)
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:31
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:31
	qw422016.N().S(``)
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:31
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:31
	qw422016.N().S(`
`)
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:33
}

//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:33
func WriteGenerateDictionaryEntry(qq422016 qtio422016.Writer, props GenerateDictionaryEntryProps) {
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:33
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:33
	StreamGenerateDictionaryEntry(qw422016, props)
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:33
	qt422016.ReleaseWriter(qw422016)
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:33
}

//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:33
func GenerateDictionaryEntry(props GenerateDictionaryEntryProps) string {
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:33
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:33
	WriteGenerateDictionaryEntry(qb422016, props)
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:33
	qs422016 := string(qb422016.B)
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:33
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:33
	return qs422016
//line ../../pkg/tempfieldprompt/GenerateDictionaryEntry.qtpl:33
}
