// Code generated by qtc from "WordSplitterPrompt.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:1
package tempfieldprompt

//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:1
import "api-go/pkg/genjsonschema"

//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:3
type WordSplitterProps struct {
	TermNeutralJsonSchema      string
	PromptParameterDefinitions []genjsonschema.PromptParameterDefinition
	ParamValues                map[string]string
}

//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:10
func StreamWordSplitterPrompt(qw422016 *qt422016.Writer, props WordSplitterProps) {
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:10
	qw422016.N().S(`
You are a stateless software function named `)
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:10
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:10
	qw422016.N().S(`WordSplitter`)
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:10
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:10
	qw422016.N().S(`.
Your input parameters:
`)
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:10
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:10
	qw422016.N().S(``)
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:10
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:10
	qw422016.N().S(``)
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:10
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:10
	qw422016.N().S(`json
[
`)
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:15
	for _, parameterDefinition := range props.PromptParameterDefinitions {
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:15
		qw422016.N().S(`  {
    "name": "`)
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:17
		qw422016.N().S(parameterDefinition.Name)
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:17
		qw422016.N().S(`",
    "description": "`)
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:18
		qw422016.N().S(parameterDefinition.ParameterDescription)
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:18
		qw422016.N().S(`",
    "value": "`)
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:19
		qw422016.N().S(props.ParamValues[parameterDefinition.Name])
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:19
		qw422016.N().S(`"
  },
`)
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:21
	}
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:21
	qw422016.N().S(`]
`)
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:21
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:21
	qw422016.N().S(``)
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:21
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:21
	qw422016.N().S(``)
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:21
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:21
	qw422016.N().S(`

The purpose of this function is to split text into individual words and convert them to their neutral grammatical forms:
1. Identify all unique meaningful words in the text (excluding punctuation and functional words if appropriate)
2. For each word, determine its base/neutral form:
   - For verbs: infinitive form
   - For nouns: singular form
   - For adjectives: masculine singular form 
   - For other word types: appropriate dictionary form
3. Return a list of these terms in their neutral forms along with their language code

Return **only** a single, JSON object matching this schema:
`)
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:21
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:21
	qw422016.N().S(``)
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:21
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:21
	qw422016.N().S(``)
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:21
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:21
	qw422016.N().S(`json
`)
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:36
	qw422016.N().S(props.TermNeutralJsonSchema)
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:36
	qw422016.N().S(`
`)
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:36
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:36
	qw422016.N().S(``)
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:36
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:36
	qw422016.N().S(``)
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:36
	qw422016.N().S("`")
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:36
	qw422016.N().S(`
`)
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:38
}

//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:38
func WriteWordSplitterPrompt(qq422016 qtio422016.Writer, props WordSplitterProps) {
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:38
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:38
	StreamWordSplitterPrompt(qw422016, props)
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:38
	qt422016.ReleaseWriter(qw422016)
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:38
}

//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:38
func WordSplitterPrompt(props WordSplitterProps) string {
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:38
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:38
	WriteWordSplitterPrompt(qb422016, props)
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:38
	qs422016 := string(qb422016.B)
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:38
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:38
	return qs422016
//line ../../pkg/tempfieldprompt/WordSplitterPrompt.qtpl:38
}
