name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-langtools-utils:
    name: Test langtools-utils
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "langtools-utils/uv.lock"
      
      - name: Set up Python
        run: uv python install 3.10
      
      - name: Install dependencies
        run: |
          cd langtools-utils
          uv sync --all-extras
      
      - name: Run tests
        run: |
          cd langtools-utils
          uv run pytest -v

  test-langtools-ai:
    name: Test langtools-ai
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "langtools-ai/uv.lock"
      
      - name: Set up Python
        run: uv python install 3.10
      
      - name: Install dependencies
        run: |
          cd langtools-ai
          uv sync --all-extras
      
      - name: Run tests
        run: |
          cd langtools-ai
          uv run pytest -v

  test-langtools-main:
    name: Test langtools-main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "langtools-main/uv.lock"
      
      - name: Set up Python
        run: uv python install 3.10
      
      - name: Install dependencies
        run: |
          cd langtools-main
          uv sync --all-extras
      
      - name: Run tests
        run: |
          cd langtools-main
          uv run pytest -v

  test-langtools-mcp:
    name: Test langtools-mcp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "langtools-mcp/uv.lock"
      
      - name: Set up Python
        run: uv python install 3.10
      
      - name: Install dependencies
        run: |
          cd langtools-mcp
          uv sync --all-extras
      
      - name: Run tests
        run: |
          cd langtools-mcp
          uv run pytest -v